// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyfopmoPmmj19db1A4y6O0aWbn-nlScvg',
    appId: '1:751550606012:web:eec6de1230500214107eb9',
    messagingSenderId: '751550606012',
    projectId: 'my-task-manager-8a969',
    authDomain: 'my-task-manager-8a969.firebaseapp.com',
    databaseURL: 'https://my-task-manager-8a969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-task-manager-8a969.firebasestorage.app',
    measurementId: 'G-MH2D83D0GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wK9FEA4rY994tpkKPnfCsIPTf15DFzs',
    appId: '1:751550606012:android:1f86efd8d767e56d107eb9',
    messagingSenderId: '751550606012',
    projectId: 'my-task-manager-8a969',
    databaseURL: 'https://my-task-manager-8a969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-task-manager-8a969.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP1tO4ucGlhNsMznrZ6i3XQZFWLnKmuR0',
    appId: '1:751550606012:ios:3a68e04a9f72955b107eb9',
    messagingSenderId: '751550606012',
    projectId: 'my-task-manager-8a969',
    databaseURL: 'https://my-task-manager-8a969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-task-manager-8a969.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP1tO4ucGlhNsMznrZ6i3XQZFWLnKmuR0',
    appId: '1:751550606012:ios:3a68e04a9f72955b107eb9',
    messagingSenderId: '751550606012',
    projectId: 'my-task-manager-8a969',
    databaseURL: 'https://my-task-manager-8a969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-task-manager-8a969.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyfopmoPmmj19db1A4y6O0aWbn-nlScvg',
    appId: '1:751550606012:web:a5385547c1091eb7107eb9',
    messagingSenderId: '751550606012',
    projectId: 'my-task-manager-8a969',
    authDomain: 'my-task-manager-8a969.firebaseapp.com',
    databaseURL: 'https://my-task-manager-8a969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-task-manager-8a969.firebasestorage.app',
    measurementId: 'G-V57QCNLM9V',
  );
}
